-- 2-Temp Table Oluþturma
CREATE TABLE #ISIMLER(ID INT IDENTITY(1,1), ISIM VARCHAR(100))
INSERT INTO #ISIMLER (ISIM) VALUES ('MUSA')

SELECT * FROM #ISIMLER
SELECT @@SPID -- SESSION ID deðerini verir.

CREATE TABLE ##ISIMLER(ID INT IDENTITY(1,1), ISIM VARCHAR(100))
INSERT INTO ##ISIMLER (ISIM) VALUES ('MUSA')

SELECT * FROM ##ISIMLER