-- 4-Temp Table Örnek-2
SELECT * FROM ITEMS

CREATE TABLE #RESULT (MARKA VARCHAR(100), OCAK FLOAT, SUBAT FLOAT, MART FLOAT, NISAN FLOAT, MAYIS FLOAT, HAZIRAN FLOAT, TEMMUZ FLOAT, AGUSTOS FLOAT, EYLUL FLOAT, EKIM FLOAT, KASIM FLOAT, ARALIK FLOAT)

INSERT INTO #RESULT(MARKA) 
SELECT DISTINCT BRAND FROM ITEMS

SELECT * FROM #RESULT

UPDATE #RESULT SET OCAK = 
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 1)

UPDATE #RESULT SET SUBAT = 
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 2)

UPDATE #RESULT SET MART = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 3)

UPDATE #RESULT SET NISAN = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 4)

UPDATE #RESULT SET MAYIS = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 5)

UPDATE #RESULT SET HAZIRAN = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 6)

UPDATE #RESULT SET TEMMUZ = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 7)

UPDATE #RESULT SET AGUSTOS = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 8)

UPDATE #RESULT SET EYLUL = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 9)

UPDATE #RESULT SET EKIM = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 10)

 UPDATE #RESULT SET KASIM = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 11)

UPDATE #RESULT SET ARALIK = (
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID = OD.ORDERID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE I.BRAND = #RESULT.MARKA
AND MONTH(O.DATE_) = 12)