-- 1-Anlýk Tarih-Saat Bilgisini Getiren Fonksiyonlar
SELECT GETDATE() GETDATE,
SYSDATETIME() SYSDATETIME,
SYSDATETIMEOFFSET() SYSDATETIMEOFFSET,
SYSUTCDATETIME() SYSUTCDATETIME,
CURRENT_TIMESTAMP "CURRENT_TIMESTAMP",
GETUTCDATE() GETUTCDATE