-- 2-DATEPART Fonksiyonu 
-- Bir tarih saat bilgisinin içinde belli bölümleri almak için belli bölümlere parçalamak için kullandýðýmýz bir fonksiyon.
SET DATEFIRST 1
SELECT 
DATEPART(YEAR,GETDATE()) YEAR_, 
DATEPART(MONTH,GETDATE()) MONTH_, 
DATEPART(DAY,GETDATE()) DAY_, 
DATEPART(HOUR,GETDATE()) HOUR_, 
DATEPART(MINUTE,GETDATE()) MINUTE_, 
DATEPART(SECOND,GETDATE()) SECOND_,
DATEPART(MILLISECOND,GETDATE()) MILLISECOND_,
DATEPART(DAYOFYEAR,GETDATE()) DAYOFYEAR_,
DATEPART(DW,GETDATE()) DW_,
DATEPART(WEEK,GETDATE()) WEEK_


