-- 3-DATENAME Fonksiyonu 
-- DATEPART fonksiyonunda biz bir tarih verisi içerisinde istediðimiz bir bölümü int olarak dýþarý alýyorduk. DATENAME fonksiyonunda ise bunu string olarak dýþarý alabiliyoruz.
SET DATEFIRST 1
SET LANGUAGE ENGLISH
SELECT 
DATENAME(YEAR,GETDATE()) YEAR_,
DATENAME(MONTH,GETDATE()) MONTH_,
DATENAME(DAY,GETDATE()) DAY_,
DATENAME(HOUR,GETDATE()) HOUR_,
DATENAME(MINUTE,GETDATE()) MINUTE_,
DATENAME(SECOND,GETDATE()) SECOND_,
DATENAME(MILLISECOND,GETDATE()) MILLISECOND_,
DATENAME(DAYOFYEAR,GETDATE()) DAYOFYEAR_,
DATENAME(DW,GETDATE()) DW_,
DATENAME(WEEK,GETDATE()) WEEK_




