-- 2-Cursor Uygulama

DECLARE @ID AS INT
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @BIRTHDATE AS DATE
DECLARE CRS CURSOR FOR 
	SELECT ID,NAMESURNAME,BIRTHDATE FROM CUSTOMERS 
	WHERE CITY = 'ÝSTANBUL' AND TOWN = 'ÜSKÜDAR'
OPEN CRS 
FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@BIRTHDATE
WHILE @@FETCH_STATUS = 0
BEGIN 
	PRINT @NAMESURNAME
	FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@BIRTHDATE
END
CLOSE CRS
DEALLOCATE CRS