-- 3-Cursor Ýle Kiþiye Özel Doðum Günü Mesajý Oluþturma
DECLARE @ID AS INT
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(1)
DECLARE @BIRTHDATE AS DATE
DECLARE @MSG AS VARCHAR(1000)

DECLARE CRS CURSOR FOR


SELECT ID,NAMESURNAME,GENDER,BIRTHDATE FROM CUSTOMERS 
WHERE DAY(BIRTHDATE) = DAY(GETDATE()) AND MONTH(BIRTHDATE)=MONTH(GETDATE())

OPEN CRS 
FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE
WHILE @@FETCH_STATUS = 0
BEGIN 
SET @MSG= 'Sayýn ' + @NAMESURNAME + ' '+IIF(@GENDER='E','Bey; ','Haným; ')+CHAR(13)+CONVERT(varchar,DATEDIFF(YEAR,@BIRTHDATE,GETDATE())) + '.Yaþýnýzý Kutlar, Saðlýklý Ömnürler Dileriz'+CHAR(13)+'*********************************************'
PRINT @MSG
FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE
END
CLOSE CRS
DEALLOCATE CRS


--SELECT  BIRTHDATEMESSAGE FROM CUSTOMERS
--WHERE DAY(BIRTHDATE) = DAY(GETDATE()) AND MONTH(BIRTHDATE)=MONTH(GETDATE())