-- 5-Cursor Ýle Kiþiye Özel Mail Gönderme

DECLARE @ID AS INT
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(1)
DECLARE @EMAIL AS VARCHAR(100)
DECLARE @BIRTHDATE AS DATE
DECLARE @AGE AS INT
DECLARE @MSG AS VARCHAR(1000)

DECLARE CRS CURSOR FOR
SELECT ID,NAMESURNAME,GENDER,BIRTHDATE,'sql20230724@outlook.com' EMAIL,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE FROM USERS 
WHERE DAY(BIRTHDATE) = DAY(GETDATE()) AND MONTH(BIRTHDATE)=MONTH(GETDATE())
OPEN CRS 
FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE,@EMAIL,@AGE
WHILE @@FETCH_STATUS = 0
BEGIN 
SET @MSG= 'Sayýn ' + @NAMESURNAME + ' '+IIF(@GENDER='E','Bey; ','Haným; ')+CHAR(13)+CONVERT(varchar,@AGE) + '.Yaþýnýzý Kutlar, Saðlýklý Mutlu Bir Hayat Dileriz'

EXEC msdb.dbo.sp_send_dbmail
	@profile_name='SQLMAIL',
	@recipients=@EMAIL,
	@body=@MSG,
	@subject='Doðum gününüz kutlu olsun.'

FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE,@EMAIL,@AGE
END
CLOSE CRS
DEALLOCATE CRS