BACKUP DATABASE [BACKUPTEST] TO  DISK = N'/var/opt/mssql/data/BACKUPTEST_DIFF4.bak' WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'BACKUPTEST-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
