BACKUP DATABASE [BACKUPTEST] TO  DISK = N'/var/opt/mssql/data/DIFF8.BAK' WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'BACKUPTEST-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, NO_COMPRESSION,  STATS = 10
GO
