CREATE VIEW VW_AYLARA_GORE_SATISLAR
AS
SELECT 
DATEPART(YEAR,O.DATE_) YIL,DATEPART(MONTH,O.DATE_) AY,
SUM(AMOUNT) TOPLAMMIKTAR, SUM(LINETOTAL) TOPLAMTUTAR, COUNT(OD.ID) URUNSAYISI,
COUNT(DISTINCT O.ID) AS MUSTERISAYISI
FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON O.ID = OD.ORDERID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)
