SELECT COUNT(*) FROM USERS
SELECT COUNT(*) FROM ORDERS
SELECT COUNT(*) FROM ORDERDETAILS
SELECT COUNT(*) FROM INVOICES
SELECT COUNT(*) FROM INVOICEDETAILS
SELECT COUNT(*) FROM PAYMENTS

CREATE VIEW VWORDERS
AS

SELECT 
U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,
C.COUNTRY ULKE,CT.CITY SEHIR,
T.TOWN ILCE,
A.ADDRESSTEXT ACIKADRES,
O.ID SIPARISID,O.DATE_ SIPARISTARIHI,OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI,
ITM.ITEMCODE URUNKODU,ITM.ITEMNAME URUNADI,ITM.BRAND MARKA
FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON O.ID = OD.ORDERID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ID = O.ID


SELECT * FROM VWORDERS
WHERE KULLANICIADI = 'Z_DALAMANLI'

SELECT * FROM VWORDERS
WHERE SEHIR = 'ANKARA'

SELECT SEHIR,SUM(SATIRTOPLAMI),COUNT(*) FROM VWORDERS
GROUP BY SEHIR

--Bir SQL sorgumu bir tablo gibi kullanabildiðimiz yapýlara VIEW denir. 