CREATE VIEW VW_TOP_1000_MUSTERI_LISTESI
AS 
SELECT TOP 1000
KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELNR1,TELNR2, SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI 
GROUP BY KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELNR1,TELNR2
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT * FROM VW_TOP_1000_MUSTERI_LISTESI