CREATE VIEW VW_SIPARIS_DETAYLI
AS
SELECT 
U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD,U.TELNR1, U.TELNR2,
C.COUNTRY AS ULKE, CT.CITY AS SEHIR, T.TOWN AS ILCE, A.ADDRESSTEXT AS ACIKADRES,
O.ID AS SIPARISID, 
OD.AMOUNT AS MIKTAR, OD.UNITPRICE AS BIRIMFIYAT, OD.LINETOTAL AS SATIRTOPLAMI, 
ITM.ITEMCODE AS URUNKODU, ITM.ITEMNAME AS URUNADI, ITM.BRAND AS MARKA, ITM.CATEGORY1 KATEGORI1, ITM.CATEGORY2 KATEGORI2, ITM.CATEGORY3 KATEGORI3, ITM.CATEGORY4 KATEGORI4,
CONVERT(DATE,O.DATE_) AS SIPARISTARIHI, CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
DATEPART(YEAR, O.DATE_) AS YIL ,
CASE 
	WHEN DATEPART(MONTH, O.DATE_) = 1 THEN '01.OCK'
	WHEN DATEPART(MONTH, O.DATE_) = 2 THEN '02.ÞUB'
	WHEN DATEPART(MONTH, O.DATE_) = 3 THEN '03.MAR'
	WHEN DATEPART(MONTH, O.DATE_) = 4 THEN '04.NÝS'
	WHEN DATEPART(MONTH, O.DATE_) = 5 THEN '05.MAY'
	WHEN DATEPART(MONTH, O.DATE_) = 6 THEN '06.HAZ'
	WHEN DATEPART(MONTH, O.DATE_) = 7 THEN '07.TEM'
	WHEN DATEPART(MONTH, O.DATE_) = 8 THEN '08.AÐU'
	WHEN DATEPART(MONTH, O.DATE_) = 9 THEN '09.EYL'
	WHEN DATEPART(MONTH, O.DATE_) = 10 THEN '10.EKM'
	WHEN DATEPART(MONTH, O.DATE_) = 11 THEN '11.KAS'
	WHEN DATEPART(MONTH, O.DATE_) = 12 THEN '12.ARA'
END AS AY,
CASE 
	WHEN DATEPART(DW, O.DATE_) = 2 THEN '01.PZT'
	WHEN DATEPART(DW, O.DATE_) = 3 THEN '02.SAL'
	WHEN DATEPART(DW, O.DATE_) = 4 THEN '03.ÇAR'
	WHEN DATEPART(DW, O.DATE_) = 5 THEN '04.PER'
	WHEN DATEPART(DW, O.DATE_) = 6 THEN '05.CUM'
	WHEN DATEPART(DW, O.DATE_) = 7 THEN '06.CMT'
	WHEN DATEPART(DW, O.DATE_) = 1 THEN '07.PZR'
END AS HAFTANINGUNU

FROM ORDERDETAILS AS OD INNER JOIN
ORDERS AS O ON O.ID = OD.ORDERID INNER JOIN
ITEMS AS ITM ON ITM.ID = OD.ITEMID INNER JOIN
USERS AS U ON U.ID = O.USERID INNER JOIN
ADDRESS AS A ON A.ID = O.ADDRESSID INNER JOIN
COUNTRIES AS C ON C.ID = A.COUNTRYID INNER JOIN
CITIES AS CT ON CT.ID = A.CITYID INNER JOIN
TOWNS AS T ON T.ID = A.TOWNID INNER JOIN
PAYMENTS AS P ON P.ID = O.ID