

CREATE VIEW VW_TOP10_KATEGORI
AS
-- En çok satan 10 ürün kategorisi
SELECT TOP 10
KATEGORI1,SUM(SATIRTOPLAMI) AS TOPLAMTUTAR FROM VW_SIPARIS_DETAYLI
GROUP BY KATEGORI1
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT * FROM VW_TOP10_KATEGORI