-- 2-Deðiþkene Deðer Tanýmlama(VARCHAR)
DECLARE @AD AS VARCHAR(100)
	SET @AD = 'MUSA'

DECLARE @SOYAD AS VARCHAR(100)='UYUMAZ'
	SET @SOYAD = 'UYUMAZ'

DECLARE @ADSOYAD AS VARCHAR(100)
	SET @ADSOYAD = @AD + ' ' + @SOYAD

DECLARE @UZUNLUK AS INT
	SET @UZUNLUK = LEN(@ADSOYAD)
SELECT @AD,@SOYAD,@ADSOYAD,@UZUNLUK