-- 3-Deðiþkene Deðer Tanýmlama(DATETIME)
DECLARE @DOGUMTARIHI AS DATE
DECLARE @YAS AS INT
SET @DOGUMTARIHI = '1999-02-14'

DECLARE @TARIH DATE
SET @TARIH = DATEADD(MONTH,-28,GETDATE())

SET @YAS = DATEDIFF(YEAR,@DOGUMTARIHI,@TARIH)

SELECT @YAS,@TARIH

DECLARE @TARIH AS DATETIME
SET @TARIH = '2023-07-02 13:13:02'

SELECT @TARIH
DECLARE @YIL AS INT
DECLARE @AY AS INT
DECLARE @GUN AS INT
DECLARE @SAAT AS INT
DECLARE @DAKIKA AS INT
DECLARE @SANIYE AS INT

SET @YIL = YEAR(@TARIH)
SET @AY = MONTH(@TARIH)
SET @GUN = DAY(@TARIH)
SET @SAAT = DATEPART(HOUR,@TARIH)
SET @DAKIKA = DATEPART(MINUTE,@TARIH)
SET @SANIYE = DATEPART(SECOND,@TARIH)

SELECT @TARIH,@YIL,@AY,@GUN,@SAAT,@DAKIKA,@SANIYE