-- 4-SQL Sorgusundan Gelen Deðeri Deðiþkenlere Atama
-- Deðiþkene bir deðer atýyorsanýz sonuç itibariyle deðiþken bir tane deðerdir ve bu tabloda da bir tane kolon ve bir tane satýr gelmeli ki bu deðiþkene deðer atamasý yapabilelim.
DECLARE @TOTALSALE AS FLOAT
DECLARE @TOTALAMOUNT AS FLOAT
DECLARE @ROWCOUNT AS INT

SET @TOTALSALE=(SELECT SUM(TOTALPRICE) FROM SALES WHERE CITY = 'ÝSTANBUL')
SET @TOTALAMOUNT=(SELECT SUM(AMOUNT) FROM SALES WHERE CITY = 'ÝSTANBUL')

SELECT @TOTALSALE=SUM(TOTALPRICE),@TOTALAMOUNT=SUM(AMOUNT),@ROWCOUNT=COUNT(*) FROM SALES 
WHERE CITY = 'ÝSTANBUL'

SELECT @TOTALSALE TOPLAMCIRO,@TOTALAMOUNT TOPLAMADET,@ROWCOUNT SATIRSAYISI