-- 5-SQL Sorgusuna Parametre Gönderme
DECLARE @CITY AS VARCHAR(100)
SET @CITY = 'A%'

DECLARE @BEGDATE AS DATE='2019-03-01'
DECLARE @ENDDATE AS DATE='2019-04-01'
DECLARE @BRAND AS VARCHAR(100)='U%'

DECLARE @TOTALPRICE AS FLOAT
SELECT @TOTALPRICE= SUM(TOTALPRICE) FROM SALES 
WHERE CITY LIKE @CITY 
AND DATE_ BETWEEN @BEGDATE AND @ENDDATE 
AND BRAND LIKE @BRAND

SELECT @TOTALPRICE