-- 8-Deðiþkenler Alýþtýrma-4
-- Elimizde ürünlerin bulunduðu bir tablo, müþterilerin bulunduðu bir tablo ve satýþlarýn bulunduðu bir baþka tablo var. Burada rastgele bir müþteriye, rastgele bir üründen '2021-01-01 - 2021-12-31' tarihleri arasýnda rastgele bir tarihte 1-20 arasýnda rastgele bir miktarda ürün satýþý gerçekleþtirecek scripti yazýnýz
-- Kaynak DB:LAB_TSQL_VARIANTS
-- Kaynak Tablo : LAB03

--SELECT * FROM LAB03_CUSTOMERS
--SELECT * FROM LAB03_ITEMS
--SELECT * FROM LAB03_SALES

DECLARE @CUSTOMERID AS INT
DECLARE @ITEMID AS INT
DECLARE @AMOUNT AS INT
DECLARE @DATE AS DATETIME
DECLARE @UNITPRICE AS FLOAT
DECLARE @LINETOTAL AS FLOAT

SELECT TOP 1 @ITEMID=ID,
@CUSTOMERID=(SELECT TOP 1 ID FROM LAB03_CUSTOMERS ORDER BY NEWID()),
@DATE=DATEADD(DAY,ROUND(1+(RAND() * 365),0),'2021-01-01'),
@AMOUNT=ROUND(1+(RAND() * 19),0),
@UNITPRICE=UNITPRICE,
@LINETOTAL=(@AMOUNT * @UNITPRICE)
FROM LAB03_ITEMS ORDER BY NEWID()
SET @DATE = DATEADD(SECOND,(RAND()*43200),@DATE)

INSERT INTO LAB03_SALES([ITEMID],[CUSTOMERID], [DATE_], [AMOUNT], [UNITPRICE], [LINETOTAL]) VALUES(@ITEMID,@CUSTOMERID,@DATE,@AMOUNT,@UNITPRICE,@LINETOTAL)


SELECT * FROM LAB03_SALES
--SELECT @CUSTOMERID,@DATE,@AMOUNT,@UNITPRICE,@LINETOTAL

--SELECT 8*12*12

SELECT C.NAMESURNAME,I.ITEMNAME,S.* FROM LAB03_SALES S
JOIN LAB03_ITEMS I ON I.ID = S.ITEMID
JOIN LAB03_CUSTOMERS C ON C.ID = S.CUSTOMERID