-- 9-Deðiþkenler Alýþtýrma-5
-- Elimizde bir satýþlar tablosu var bir de müþteriler tablosu var. Bu tablodan rastgele seçilen 10 müþteriye bu zamana kadar yapmýþ olduðu alýiveriþin %50'si kadar hediye çeki verme kampanyasý yapýlmasý planlanýyor. Bir script ile 10 müþteri ve bu 10 müþteriye verilecek hediye çeklerini hesaplayan T-SQL cümlesini yazýnýz.
-- Kaynak DB:LAB_TSQL_VARIANTS
-- Kaynak Tablo : LAB04

DECLARE @IDS TABLE(ID INT)
DECLARE @RAND FLOAT = ROUND(0.01 + (RAND() * 0.49),2)
DECLARE @CUSTOMERID INT
DECLARE @CUSTOMERNAMESURNAME VARCHAR(100)
DECLARE @TOTALPRICE FLOAT
DECLARE @GIFTPERCENT FLOAT
DECLARE @GIFTTOTAL FLOAT

INSERT INTO @IDS(ID)
SELECT TOP 10 ID FROM LAB04_CUSTOMERS ORDER BY NEWID()

SELECT @CUSTOMERID=CUSTOMERID,@CUSTOMERNAMESURNAME=C.CUSTOMERNAME,@TOTALPRICE=SUM(TOTALPRICE)FROM LAB04_SALES S
JOIN LAB04_CUSTOMERS C ON C.ID = S.CUSTOMERID
WHERE CUSTOMERID IN(SELECT ID FROM @IDS)
AND C.ID NOT IN (SELECT CUSTOMERID FROM RAFFLE)
GROUP BY CUSTOMERID,C.CUSTOMERNAME

--SELECT @CUSTOMERID CUSTOMERID,@CUSTOMERNAMESURNAME CUSTOMERNAMESURNAME,@TOTALPRICE TOPLAMTUTAR,ROUND((@TOTALPRICE * @RAND),2)HEDIYEKUPONU, (@RAND * 100) KUPONORANI

SET @GIFTPERCENT = (@RAND * 100)
SET @GIFTTOTAL = ROUND((@TOTALPRICE * @RAND),2)

INSERT INTO RAFFLE([CUSTOMERID], [CUSTOMERNAME], [TOTALSALE], [GIFTPERCENT], [GIFTTOTAL]) 
VALUES(@CUSTOMERID,@CUSTOMERNAMESURNAME,@TOTALPRICE,@GIFTPERCENT,@GIFTTOTAL)
SELECT * FROM RAFFLE

--CREATE TABLE RAFFLE(ID INT IDENTITY(1,1), CUSTOMERID INT, CUSTOMERNAME VARCHAR(100), TOTALSALE FLOAT,GIFTPERCENT FLOAT, GIFTTOTAL FLOAT)
--SELECT * FROM LAB04_CUSTOMERS

