-- 11- User Defined Functions Alýþtýrma-4
-- Elimizde bir futbolcu listesi var ve futbolcularýn oynadýðý maçlarýn listesi var.
-- Her bir futbolcunun
-- Yaþýný, Yaþ grubunu
-- Futbolcunun puanýný
-- Kaç kez yedek kadroda çýktýðýný
-- Kaç kez asil kadroda çýktýðýný,
-- Kaç farklý takýmda oynadýðýný,
-- Toplam kaç maç yaptýðýný,
-- Kaç yýldýr futbol oynadýðýný getiren table valued fonksiyonu inline olarak yazýnýz.
-- Kaynak DB: LAB_UDF
-- Kaynak Tablo: LAB_PLAYER, LAB_MATCH_PLAYER

ALTER FUNCTION DBO.GETPLAYERINFO(@PLAYERID AS INT)
RETURNS TABLE 
RETURN(
SELECT PLAYER_API_ID,PLAYER_NAME,
(SELECT TOP 1 TEAM FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID ORDER BY DATE_ DESC) TEAMNAME,
DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE,
CASE
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) < 20 THEN '20 DEN KÜÇÜK'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 THEN '20-30 ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 31 AND 40 THEN '31-40 ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 40 THEN '40 TAN BÜYÜK'
END AS AGEGROUP,
(SELECT COUNT(*) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID AND PLAYERTYPE='BACKUP') BACKUPCOUNT,
(SELECT COUNT(*) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID AND PLAYERTYPE='REAL') REALCOUNT,
(SELECT COUNT(DISTINCT TEAM) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) TEAMCOUNT,
(SELECT COUNT(*) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) MATCHCOUNT,
(SELECT DATEDIFF(YEAR,MIN(DATE_),MAX(DATE_)) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) TOTALYEAR,
(SELECT MIN(DATE_)FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) FIRSTMATCHDATE,
(SELECT MAX(DATE_) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) LASTMATCHDATE,
RATING
FROM LAB_PLAYER P WHERE PLAYER_API_ID = @PLAYERID
)
SELECT INF.* FROM LAB_PLAYER P
CROSS APPLY dbo.GETPLAYERINFO(P.PLAYER_API_ID) INF
ORDER BY INF.RATING DESC


--CREATE FUNCTION PLAYERINFO(@PLAYERID AS INT)
--RETURNS TABLE
--AS
--RETURN
--(
	
--)