-- 2-Scalar Valued Functions
CREATE FUNCTION DBO.TOPLA(@SAYI1 AS INT, @SAYI2 AS INT)
RETURNS INT
AS 
BEGIN
	RETURN @SAYI1 + @SAYI2
END

SELECT DBO.TOPLA(30,15)

ALTER FUNCTION DBO.TOPLA(@SAYI1 AS INT, @SAYI2 AS INT)
RETURNS INT
AS 
BEGIN
	DECLARE @SONUC AS INT
	SET @SONUC = @SAYI1 + @SAYI2
	RETURN @SONUC
END

SELECT DBO.TOPLA(15,20)