-- 4-Tablodan Deðer Döndüren Fonksiyonlar
SELECT I.ID,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.BRAND,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOTALAMOUNT
FROM ITEMS I

CREATE FUNCTION DBO.GETTOTALAMOUNT(@ITEMID INT)
RETURNS INT
AS 
BEGIN
	DECLARE @RESULT AS INT
	SELECT @RESULT = SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=@ITEMID
	RETURN @RESULT
END

SELECT dbo.GETTOTALAMOUNT(2)

SELECT I.ID,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.BRAND,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOTALAMOUNT,
dbo.GETTOTALAMOUNT(I.ID) TOTALAMOUNT2
FROM ITEMS I

CREATE FUNCTION DBO.GETTOTALSALE(@ITEMID INT)
RETURNS FLOAT
AS 
BEGIN
	DECLARE @RESULT AS FLOAT
	SELECT @RESULT = SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=@ITEMID
	RETURN @RESULT
END

SELECT I.ID,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.BRAND,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOTALAMOUNT,
dbo.GETTOTALAMOUNT(I.ID) TOTALAMOUNT2,
dbo.GETTOTALSALE(I.ID) TOTALSALE
FROM ITEMS I