-- 5-Neden Table Valued Function
CREATE FUNCTION DBO.GETMINPRICE(@ITEMID INT)
RETURNS FLOAT
AS 
BEGIN 
	DECLARE @RESULT AS FLOAT
	SELECT @RESULT=MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = @ITEMID
	RETURN @RESULT
END

SELECT I.ID,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.BRAND,
dbo.GETTOTALAMOUNT(I.ID) TOTALAMOUNT,
dbo.GETTOTALSALE(I.ID) TOTALSALE,
DBO.GETMINPRICE(I.ID) MINPRICE
FROM ITEMS I

CREATE FUNCTION DBO.GETMAXPRICE(@ITEMID INT)
RETURNS FLOAT
AS 
BEGIN 
	DECLARE @RESULT AS FLOAT
	SELECT @RESULT=MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = @ITEMID
	RETURN @RESULT
END

SELECT I.ID,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.BRAND,
dbo.GETTOTALAMOUNT(I.ID) TOTALAMOUNT,
dbo.GETTOTALSALE(I.ID) TOTALSALE,
DBO.GETMINPRICE(I.ID) MINPRICE,
DBO.GETMAXPRICE(I.ID) MAXPRICE
FROM ITEMS I

CREATE FUNCTION DBO.GETAVGPRICE(@ITEMID INT)
RETURNS FLOAT
AS 
BEGIN 
	DECLARE @RESULT AS FLOAT
	SELECT @RESULT=AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = @ITEMID
	RETURN @RESULT
END

SELECT I.ID,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.BRAND,
dbo.GETTOTALAMOUNT(I.ID) TOTALAMOUNT,
dbo.GETTOTALSALE(I.ID) TOTALSALE,
DBO.GETMINPRICE(I.ID) MINPRICE,
DBO.GETMAXPRICE(I.ID) MAXPRICE,
dbo.GETAVGPRICE(I.ID) AVGPRICE
FROM ITEMS I