-- 7- Multi Statement Table Valued Function

CREATE FUNCTION DBO.ITEMIFO2(@ITEMID INT)
RETURNS 
@RESULT TABLE
(
	ID INT,
	ITEMCODE VARCHAR(50),
	ITEMNAME VARCHAR(100),
	TOTALAMOUNT INT,
	TOTALSALE FLOAT,
	MINPRICE FLOAT,
	MAXPRICE FLOAT,
	AVGPRICE FLOAT
)
AS
BEGIN 
	INSERT INTO @RESULT(ID,ITEMCODE,ITEMNAME,TOTALAMOUNT,TOTALSALE,MINPRICE,MAXPRICE,AVGPRICE)
	SELECT I.ID,I.ITEMCODE,I.ITEMNAME ,SUM(OD.AMOUNT) TOTALAMOUNT, SUM(OD.LINETOTAL) TOTALSALE,
	MIN(OD.UNITPRICE) MINPRICE,MAX(OD.UNITPRICE) MAXPRICE,AVG(OD.UNITPRICE) AVGPRICE
	FROM ITEMS I
	JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
	WHERE I.ID = @ITEMID
	GROUP BY I.ID,I.ITEMCODE,I.ITEMNAME
	RETURN
END

SELECT * FROM dbo.ITEMIFO2(1)