-- 5-Þart Bloklarý Alýþtýrma-2
-- Elimizde plaka bilgileri ile birlikte araç verilerinin tutulduðu bir tablo var. Bu tabloda araçlarýn marka bazýnda model yýlý ile trafiðe çýkýþ zamaný arasýndaki farka göre sayýsýný getirecek sorguyu yazýnýz
-- Kaynak DB:LAB_CONDITION_BLOCKS
-- Kaynak Tablo:LAB02

SELECT BRAND,
CASE
	WHEN DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 0 THEN 'AYNI YIL TRAFÝÐE ÇIKMIÞ'
	WHEN DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 1 THEN 'BÝR YIL SONRA TRAFÝÐE ÇIKMIÞ'
	WHEN DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 2 THEN 'ÝKÝ YIL SONRA TRAFÝÐE ÇIKMIÞ'
END AS STATUS_,
COUNT(*) COUNT_
FROM LAB02
GROUP BY BRAND,DATEDIFF(YEAR,YEAR_,LICENCEDATE)
ORDER BY 1,2

-- ÝKÝ SEÇENEKLÝ
SELECT BRAND,
IIF(DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 0,'AYNI YIL TRAFÝÐE ÇIKMIÞ','ÜRETÝM TARÝHÝNDEN SONRAKÝ YILLARDA TRAFÝÐE ÇIKMIÞ') STATUS_,
COUNT(*) COUNT_
FROM LAB02
GROUP BY BRAND,IIF(DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 0,'AYNI YIL TRAFÝÐE ÇIKMIÞ','ÜRETÝM TARÝHÝNDEN SONRAKÝ YILLARDA TRAFÝÐE ÇIKMIÞ')
ORDER BY 1,2
