-- 6-Þart Bloklarý Alýþtýrma-3
-- Elimizde bir satýþ verisi var. Bu veride her bir þehirde erkeklerin ve kadýnlarýn ne kadar alýþveriþ yaptýðýný ve birbirine oranýný bulunuz ve toplam ciro rakamýndaki orana göre her bir þehir için kadýnlarýn ortalamanýn altýnda mý yoksa üstünde mi alýþveriþ yaptýðýný hesaplayýnýz.
-- Kaynak DB:LAB_CONDITION_BLOCKS
-- Kaynak Tablo:LAB03


SELECT CITY,SUM(TOTALPRICE) TOTALPRICE,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='K' AND CITY = L.CITY) FEMALESALE,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='E' AND CITY = L.CITY) MALESALE,
IIF(((SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='K' AND CITY = L.CITY) + (SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='E' AND CITY = L.CITY))/ 2 > (SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='K' AND CITY = L.CITY),'ORTALAMADAN DÜÞÜK','ORTALAMADAN YÜKSEK') FEMALE_MALE_RATIO,
((SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='K' AND CITY = L.CITY) + (SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='E' AND CITY = L.CITY)) / 2 RATIO
FROM LAB03 L
GROUP BY CITY
ORDER BY 1



SELECT *,
(FEMALESALE+MALESALE)/2 AS RATIO,
IIF((FEMALESALE+MALESALE)/2 > FEMALESALE,'ORTALAMADAN DÜÞÜK','ORTALAMADAN YÜKSEK') FEMALE_MALE_RATIO
FROM
(
	SELECT DISTINCT CITY,
	(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='K' AND CITY = L.CITY) FEMALESALE,
	(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER ='E' AND CITY = L.CITY) MALESALE
	FROM LAB03 L
) T 
ORDER BY 1