SELECT * FROM ITEMS WHERE ID=1
SELECT * FROM ITEMTRANSACTIONS WHERE ITEMID=1
SELECT * FROM ITEMTRANSACTIONS WHERE ID=4
SELECT * FROM STOCK WHERE ITEMID=1

UPDATE ITEMTRANSACTIONS SET AMOUNT=10 WHERE ID=4

UPDATE ITEMTRANSACTIONS SET AMOUNT=20 WHERE ID=2638