
SELECT * FROM ITEMS

SELECT IOTYPE,SUM(AMOUNT),COUNT(IOTYPE) FROM ITEMTRANSACTIONS WHERE ITEMID=1
GROUP BY IOTYPE

SET STATISTICS IO ON
SELECT ID,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID=ITM.ID AND IOTYPE=1)
-
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID=ITM.ID AND IOTYPE=2) STOK
FROM ITEMS ITM

SET STATISTICS IO ON
SELECT * FROM STOCK