--TRUNCATE TABLE ITEMTRANSACTIONS

SELECT * FROM ITEMTRANSACTIONS

INSERT INTO ITEMTRANSACTIONS([ITEMID], [DATE_], [AMOUNT], [IOTYPE]) 
VALUES(1,GETDATE(),3,2)

UPDATE STOCK SET STOCK=0

SELECT * FROM ITEMTRANSACTIONS
SELECT * FROM STOCK

--TRUNCATE TABLE STOCK

TRUNCATE TABLE ITEMTRANSACTIONS