DECLARE @I AS INT =100
WHILE @I < 501
BEGIN 
INSERT INTO ITEMS([ITEMCODE], [ITEMNAME])
VALUES('URUN'+CAST(@I AS VARCHAR), 'URUN ' +CAST(@I AS VARCHAR))

SET @I = @I+1
END


--TRUNCATE TABLE ITEMS
SELECT * FROM ITEMS