SELECT MAX(WORKERID),COUNT(*) FROM WORKERTRANSACTIONS

SET STATISTICS IO ON
SELECT *,
(SELECT TOP 1 IOTYPE FROM WORKERTRANSACTIONS WHERE WORKERID=W.ID ORDER BY DATE_ DESC) SONHAREKETTURU,
(SELECT MAX(DATE_) IOTYPE FROM WORKERTRANSACTIONS WHERE WORKERID=W.ID) SONHAREKETZAMANI

FROM WORKERS W
ORDER BY ID

INSERT INTO WORKERLASTTRANSACTIONS([WORKERID])
SELECT ID FROM WORKERS

SELECT * FROM WORKERLASTTRANSACTIONS