CREATE TRIGGER TRG_ITEMS_DELETE_UPDATE
ON ITEMS
AFTER DELETE,UPDATE
AS 
BEGIN
DECLARE @DELETEDCOUNT AS INT
DECLARE @INSERTEDCOUNT AS INT
DECLARE @LOG_ACTIONTYPE AS VARCHAR(20)

SELECT @DELETEDCOUNT=COUNT(*) FROM DELETED
SELECT @INSERTEDCOUNT=COUNT(*) FROM INSERTED

IF @DELETEDCOUNT>0 AND @INSERTEDCOUNT>0
	SET @LOG_ACTIONTYPE='UPDATE'
IF @DELETEDCOUNT>0 AND @INSERTEDCOUNT=0
	SET @LOG_ACTIONTYPE='DELETE'

INSERT INTO ITEMS_LOG([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])

SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND],@LOG_ACTIONTYPE,GETDATE(),USER_NAME(),PROGRAM_NAME(),HOST_NAME() FROM DELETED
END

SELECT SUSER_NAME()
SELECT PROGRAM_NAME()
SELECT HOST_NAME()