SELECT ID,WORKERCODE,WORKERNAME,GENDER,BIRTHDATE,TCNO,WORKERBARCODE FROM WORKERS

SELECT TOP 1000 
TCNO AS WORKERCODE,NAMESURNAME AS WORKERNAME,GENDER,BIRTHDATE,TCNO,NEWID() AS WORKERBARCODE

FROM CRM2.DBO.CUSTOMERS

--TRUNCATE TABLE WORKERS

INSERT INTO WORKERS(WORKERCODE,WORKERNAME,GENDER,BIRTHDATE,TCNO,WORKERBARCODE)
SELECT TOP 1000 
TCNO AS WORKERCODE,NAMESURNAME AS WORKERNAME,GENDER,BIRTHDATE,TCNO,NEWID() AS WORKERBARCODE
FROM CRM2.DBO.CUSTOMERS

SELECT * FROM WORKERS

SELECT COUNT(*) FROM WORKERTRANSACTIONS