-- 1-Pivot Kavramý
-- Özet tablo oluþturma Satýrlarý sütuna sütunlarý satýra çevirme iþlemleri.

SELECT T.CATEGORY1,SUM(T.TOTALSALE_M) TOTALSALE_M,SUM(T.TOTALSALE_W) TOTALSALE_W FROM 
(
SELECT 
CATEGORY1,
CASE WHEN CUSTOMERGENDER ='E' THEN SUM(TOTALPRICE) ELSE 0 END AS TOTALSALE_M,
CASE WHEN CUSTOMERGENDER ='K' THEN SUM(TOTALPRICE) ELSE 0 END AS TOTALSALE_W,
CUSTOMERGENDER,SUM(TOTALPRICE) TOTALSALE
FROM SALES
GROUP BY CATEGORY1,CUSTOMERGENDER
) T
GROUP BY CATEGORY1


SELECT CATEGORY1,CATEGORY2,[E],[K]
FROM
(
SELECT 
CATEGORY1,CATEGORY2,CUSTOMERGENDER,TOTALPRICE
FROM SALES
)SOURCETABLE
PIVOT
(
SUM(TOTALPRICE) FOR CUSTOMERGENDER IN ([E],[K])
)PVT
