-- 2- Pivot Uygulama
SET LANGUAGE TURKISH
SELECT CITY,[OCAK],[ÞUBAT],[MART],[NÝSAN],[MAYIS],[HAZÝRAN],[TEMMUZ],[AÐUSTOS],[EYLÜL],[EKÝM],[KASIM],[ARALIK]
FROM 
(
	SELECT CITY,DATENAME(MONTH,DATE_) MONTH_,TOTALPRICE FROM SALES
)AS ST
PIVOT
(
SUM(TOTALPRICE) FOR MONTH_ IN( [OCAK],[ÞUBAT],[MART],[NÝSAN],[MAYIS],[HAZÝRAN],[TEMMUZ],[AÐUSTOS],[EYLÜL],[EKÝM],[KASIM],[ARALIK])
)AS PVT