-- === Multiple Actions TRIGGER ===
CREATE TRIGGER MULTITRIGGER
ON PERSONELLER
AFTER DELETE, INSERT
AS 
PRINT 'MERHABA'

INSERT Personeller(Adi,SoyAdi) VALUES('MUSA','UYUMAZ')
DELETE FROM Personeller WHERE PersonelID = 30