-- === DDL TRIGGERLAR ===
-- CREATE, ALTER ve DROP iþlemleri sonucunda veya sürecinde devreye girecek olan yapýlardýr.
CREATE TRIGGER DDL_TRIGGER
ON DATABASE
FOR DROP_TABLE, ALTER_TABLE, CREATE_FUNCTION, CREATE_PROCEDURE, DROP_PROCEDURE --VS. VS.
AS
PRINT 'BU ÝÞLEM GERÇEKLEÞTÝRÝLEMEZ'
ROLLBACK

DROP TABLE LOGTABLOSU