-- PARTITION BY Komutu Ýle Gruplama

-- PROTOTÝP
-- SELECT ROW_NUMBER() OVER(PARTITION BY KOLON1 ORDER BY KOLON2) INDEXER, * FROM TABLO

SELECT ROW_NUMBER() OVER(PARTITION BY MusteriID ORDER BY OdemeTarihi) INDEXER,* FROM Satislar ORDER BY SatisID