-- == Dynamic Data Masking Nasýl Uygulanýr? ==

-- Prototip

-- CREATE TABLE [TABLO ADI]
--(
-- [KOLON ADI] [KOLON TÝPÝ] MASKED WITH(FUNCTION = 'DEFAULT()')
--)

CREATE TABLE OGRENCILER2
(
	OGRENCIID INT PRIMARY KEY IDENTITY,
	ADI NVARCHAR(10) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	SOYADI NVARCHAR(10) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	MEMLEKETI NVARCHAR(10) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	TCNO INT MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	SUBE NVARCHAR(1) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
	EMAIL NVARCHAR(MAX) MASKED WITH (FUNCTION = 'EMAIL()') NULL,
	HAKKINDA NVARCHAR(MAX) MASKED WITH (FUNCTION = 'PARTIAL(3,"H",2)') NULL,
	DOGUMTARIHI DATETIME MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
)

INSERT OGRENCILER2 VALUES('MUSA','UYUMAZ','ESKÝÞEHÝR',1234,'A','musa.uyumaz73@gmail.com','Türk Milletine Caným Feda Olsun...','1999-02-14')
INSERT OGRENCILER2 VALUES('GENÇAY','YILDIZ','ARTVÝN',1234,'A','gncy@gencayyildiz.com','Türk Milletine Caným Feda Olsun...','1992-09-05')
INSERT OGRENCILER2 VALUES('ÝBRAHÝM','YILDIRIM','MALATYA',1234,'B','ibrahim@yildirim.com','Türk Milletine Caným Feda Olsun...','1975-09-05')

SELECT * FROM OGRENCILER2

CREATE USER YETKILIUSER WITHOUT LOGIN --YETKILIUSER isminde bir kullanýcý oluþturuluyor.
GO 
GRANT SELECT ON OGRENCILER2 TO YETKILIUSER --YETKILIUSER isimli kullanýcýya OGRENCILER2 tablosunda SELECT yetkisi veriliyor.

EXECUTE AS USER = 'YETKILIUSER' -- YETKILIUSER isimli kullanýcýya geçiþ saðlýyoruz.

SELECT * FROM OGRENCILER2