-- == Temporal Table Çalýþma Mekanizmasý ==
UPDATE DERSKAYITLARI SET DERS = 'MATEMATÝK2' WHERE DERSID = 1
UPDATE DERSKAYITLARI SET DERS = 'FÝZÝK2' WHERE DERSID = 2
UPDATE DERSKAYITLARI SET DERS = 'KÝMYA2' WHERE DERSID = 3
UPDATE DERSKAYITLARI SET DERS = 'KÝMYA3' WHERE DERSID = 3
UPDATE DERSKAYITLARI SET DERS = 'BÝYOLOJÝ2' WHERE DERSID = 4
UPDATE DERSKAYITLARI SET DERS = 'BÝYOLOJÝ3' WHERE DERSID = 4

SELECT * FROM DERSKAYITLARI
SELECT * FROM DERSKAYITLARILOG