-- IF - ELSE IF - ELSE Yapýsý

DECLARE @ADI NVARCHAR(MAX) = 'MUSA'
DECLARE @YAS INT = 24

IF @ADI = 'MAHMUT'
	PRINT 'EVET MAHMUT'
ELSE IF @YAS > 23
	PRINT 'YAÞI 23''TEN BÜYÜK'
ELSE IF 3 > 5
	BEGIN
		PRINT ''
	END
ELSE IF 1 = 1
	PRINT 'EÞÝT'
ELSE
	PRINT 'ABC'