--Stored Procedur'ler içerisinde T-SQL bir kod topluluðudur. ayný zamanda bir database objesi olduðu için CREATE ile oluþturulur ALTER ile deðiþtirilir ve DROP'la da silinir

SELECT * FROM WORKERS WHERE WORKERBARCODE = '9807BCEA-F5BC-4D93-B17A-72819E17CD7B'

CREATE PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS 
BEGIN
SELECT * FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
END

ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS 
BEGIN
	IF EXISTS(SELECT * FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE)
		BEGIN
			SELECT 'KART DOÐRU'
		END
	ELSE 
		BEGIN
			SELECT 'KART GEÇERSÝZ'
		END
END

ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS 
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)
	SELECT @WORKERNAME= WORKERNAME FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
	IF @WORKERNAME IS NULL
		BEGIN 
			RAISERROR('KART GEÇERSÝZ',16,1)
			RETURN
		END
	ELSE
		BEGIN
			SELECT @WORKERNAME
		END
END