--Biz her Procedure'e mühadale edemeyebiliriz.
	-- Bu bir sistem procedürü olabilir.
	-- Bu procedure müdahale etmeye yetkimiz olmayabilir.
	-- Bu procedure çok fazla yerde kullanýlýyordur bizim müdahalemiz sonucu bozulabilir.
	-- Bu procedure çok karmaþýktýr ve müdahale ettiðimiz zaman biz onun yapýsýný bozabiliriz.

-- Eðer biz müdahale edemediðimiz bir procedure'ü filtrelemek istersek eðer bir tabloya Stored Procedure datalarýný atabiliriz. Ýþte burada devreye temp db'ler girer.

CREATE TABLE RAPOR
(KULLANICIADI VARCHAR(100),ADSOYAD VARCHAR(100), TELNR1 VARCHAR(100), TELNR2 VARCHAR(100), ULKE VARCHAR(100),
SEHIR VARCHAR(100), ILCE VARCHAR(100), ACIKADRES VARCHAR(500), SIPARISID INT, MIKTAR FLOAT,BIRIMFIYAT FLOAT, 
SATIRTOPLAMI FLOAT, URUNKODU VARCHAR(100), 
URUNADI VARCHAR(100), MARKA VARCHAR(100), KATEGORI1 VARCHAR(100),KATEGORI2 VARCHAR(100), KATEGORI3 VARCHAR(100),
KATEGORI4 VARCHAR(100),  SIPARISTARIHI DATE, SIPARISZAMANI TIME,
YIL INT, AY VARCHAR(50), HAFTANINGUNU VARCHAR(50)
)

INSERT INTO RAPOR
EXEC SP_SATISLAR '20190101','20190131'

SELECT * FROM RAPOR WHERE KATEGORI1 = 'GIDA'

SELECT KATEGORI1,SUM(SATIRTOPLAMI) FROM RAPOR GROUP BY KATEGORI1

DROP TABLE RAPOR

CREATE TABLE #RAPOR
(KULLANICIADI VARCHAR(100),ADSOYAD VARCHAR(100), TELNR1 VARCHAR(100), TELNR2 VARCHAR(100), ULKE VARCHAR(100),
SEHIR VARCHAR(100), ILCE VARCHAR(100), ACIKADRES VARCHAR(500), SIPARISID INT, MIKTAR FLOAT,BIRIMFIYAT FLOAT, 
SATIRTOPLAMI FLOAT, URUNKODU VARCHAR(100), 
URUNADI VARCHAR(100), MARKA VARCHAR(100), KATEGORI1 VARCHAR(100),KATEGORI2 VARCHAR(100), KATEGORI3 VARCHAR(100),
KATEGORI4 VARCHAR(100),  SIPARISTARIHI DATE, SIPARISZAMANI TIME,
YIL INT, AY VARCHAR(50), HAFTANINGUNU VARCHAR(50)
)

INSERT INTO #RAPOR
EXEC SP_SATISLAR '20190101','20190131'

SELECT KATEGORI1,SUM(SATIRTOPLAMI) FROM #RAPOR GROUP BY KATEGORI1

DROP TABLE #RAPOR