CREATE PROC SP_SATISLAR
@BASTARIH DATE,
@BITTARIH DATE
AS
BEGIN 	
	SELECT 
	U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD,U.TELNR1, U.TELNR2,
	C.COUNTRY AS ULKE, CT.CITY AS SEHIR, T.TOWN AS ILCE, A.ADDRESSTEXT AS ACIKADRES,
	O.ID AS SIPARISID, 
	OD.AMOUNT AS MIKTAR, OD.UNITPRICE AS BIRIMFIYAT, OD.LINETOTAL AS SATIRTOPLAMI, 
	ITM.ITEMCODE AS URUNKODU, ITM.ITEMNAME AS URUNADI, ITM.BRAND AS MARKA, ITM.CATEGORY1 KATEGORI1, ITM.CATEGORY2 KATEGORI2,	ITM.CATEGORY3 KATEGORI3, ITM.CATEGORY4 KATEGORI4,
	CONVERT(DATE,O.DATE_) AS SIPARISTARIHI, CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
	DATEPART(YEAR, O.DATE_) AS YIL ,
	DBO.MONTHNAME_(O.DATE_) AY,
	DBO.DAYOFWEEK_(O.DATE_) HAFTANINGUNU
	
	FROM ORDERDETAILS AS OD INNER JOIN
	ORDERS AS O ON O.ID = OD.ORDERID INNER JOIN
	ITEMS AS ITM ON ITM.ID = OD.ITEMID INNER JOIN
	USERS AS U ON U.ID = O.USERID INNER JOIN
	ADDRESS AS A ON A.ID = O.ADDRESSID INNER JOIN
	COUNTRIES AS C ON C.ID = A.COUNTRYID INNER JOIN
	CITIES AS CT ON CT.ID = A.CITYID INNER JOIN
	TOWNS AS T ON T.ID = A.TOWNID INNER JOIN
	PAYMENTS AS P ON P.ID = O.ID
	
	WHERE O.DATE_ BETWEEN @BASTARIH AND @BITTARIH
END

ALTER PROC SP_SATISLAR
@BASTARIH DATE,
@BITTARIH DATE,
@SEHIR AS VARCHAR(50)='%'
AS
BEGIN 	
	SELECT 
	U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD,U.TELNR1, U.TELNR2,
	C.COUNTRY AS ULKE, CT.CITY AS SEHIR, T.TOWN AS ILCE, A.ADDRESSTEXT AS ACIKADRES,
	O.ID AS SIPARISID, 
	OD.AMOUNT AS MIKTAR, OD.UNITPRICE AS BIRIMFIYAT, OD.LINETOTAL AS SATIRTOPLAMI, 
	ITM.ITEMCODE AS URUNKODU, ITM.ITEMNAME AS URUNADI, ITM.BRAND AS MARKA, ITM.CATEGORY1 KATEGORI1, ITM.CATEGORY2 KATEGORI2,	ITM.CATEGORY3 KATEGORI3, ITM.CATEGORY4 KATEGORI4,
	CONVERT(DATE,O.DATE_) AS SIPARISTARIHI, CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
	DATEPART(YEAR, O.DATE_) AS YIL ,
	DBO.MONTHNAME_(O.DATE_) AY,
	DBO.DAYOFWEEK_(O.DATE_) HAFTANINGUNU
	
	FROM ORDERDETAILS AS OD INNER JOIN
	ORDERS AS O ON O.ID = OD.ORDERID INNER JOIN
	ITEMS AS ITM ON ITM.ID = OD.ITEMID INNER JOIN
	USERS AS U ON U.ID = O.USERID INNER JOIN
	ADDRESS AS A ON A.ID = O.ADDRESSID INNER JOIN
	COUNTRIES AS C ON C.ID = A.COUNTRYID INNER JOIN
	CITIES AS CT ON CT.ID = A.CITYID INNER JOIN
	TOWNS AS T ON T.ID = A.TOWNID INNER JOIN
	PAYMENTS AS P ON P.ID = O.ID
	
	WHERE O.DATE_ BETWEEN @BASTARIH AND @BITTARIH
	AND CT.CITY LIKE @SEHIR
END