--CURSOR, bir datasetinin içerisinde bir tablodan dönen deðerlerin içerisinde bizim döngüyle dönüp birtakým iþleri sýralý þekilde yaptýrmamýz demektir.

DECLARE @NAMESURNAME AS VARCHAR(50)
DECLARE @AGE AS INT
DECLARE @EMAIL AS VARCHAR(100)
DECLARE @MESSAGE AS VARCHAR(500)

DECLARE CRS CURSOR FOR SELECT NAMESURNAME,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE,EMAIL 
FROM USERS
WHERE DAY(BIRTHDATE) = 13 AND MONTH(BIRTHDATE)=6
OPEN CRS 
FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL

WHILE @@FETCH_STATUS=0
BEGIN 
	SET @MESSAGE='Sayýn '+@NAMESURNAME+', Doðum gününüz kutlu olsun. '+CONVERT(VARCHAR,@AGE)+'. Yaþýnýzý kutlar, nice mutlu yýllar dileriz.';

	EXEC MSDB.DBO.SP_SEND_DBMAIL @PROFILE_NAME='SQLMAIL',
	@SUBJECT='MUTLU YILLAR',
	@BODY=@MESSAGE,
	@RECIPIENTS=@EMAIL         

FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL
END
CLOSE CRS 
DEALLOCATE CRS


--SELECT *,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) FROM USERS
--WHERE DAY(BIRTHDATE) = 13 AND MONTH(BIRTHDATE)=6

--UPDATE USERS SET EMAIL='ecoffeecompanyinfo@gmail.com' WHERE DAY(BIRTHDATE) = 13 AND MONTH(BIRTHDATE)=6

