-- 2-Insert Trigger 
SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS(CUSTOMERNAME,BIRTHDATE,TELNR)
VALUES('ALÝ VELÝ','19860312','05361234567')

ALTER TRIGGER TRGCUSTOMERINSERT
ON CUSTOMERS
AFTER INSERT
AS 
BEGIN 
	DECLARE @ID AS INT
	DECLARE @CUSTOMERNAME AS VARCHAR(100)
	DECLARE @BIRTHDATE AS DATE
	DECLARE @TELNR AS VARCHAR(20)

	SELECT @ID=ID,@CUSTOMERNAME=CUSTOMERNAME,@BIRTHDATE=BIRTHDATE,@TELNR=TELNR 
	FROM inserted

	SELECT @ID ID, @CUSTOMERNAME CUSTOMERNAME,@BIRTHDATE BIRTHDATE,@TELNR TELNR
	PRINT 'INSERT ÝÞLEMÝ BAÞARI ÝLE GERÇEKLEÞTÝ'
END

TRUNCATE TABLE CUSTOMERS