-- 3-Update Delete Trigger 
CREATE TRIGGER TRGCUSTOMERDELETE
ON CUSTOMERS
AFTER DELETE
AS
BEGIN
	DECLARE @ID AS INT
	DECLARE @CUSTOMERNAME AS VARCHAR(100)
	DECLARE @BIRTHDATE AS DATE
	DECLARE @TELNR AS VARCHAR(20)

	SELECT @ID=ID,@CUSTOMERNAME=CUSTOMERNAME,@BIRTHDATE=BIRTHDATE,@TELNR=TELNR 
	FROM deleted

	SELECT @ID ID, @CUSTOMERNAME CUSTOMERNAME,@BIRTHDATE BIRTHDATE,@TELNR TELNR
	PRINT 'SÝLME ÝÞLEMÝ BAÞARI ÝLE GERÇEKLEÞTÝ'
END

SELECT * FROM CUSTOMERS
DELETE FROM CUSTOMERS WHERE ID=2

CREATE TRIGGER TRGCUSTOMERUPDATE
ON CUSTOMERS
AFTER UPDATE
AS
BEGIN
	DECLARE @ID AS INT
	DECLARE @OLD_CUSTOMERNAME AS VARCHAR(100)
	DECLARE @OLD_BIRTHDATE AS DATE
	DECLARE @OLD_TELNR AS VARCHAR(20)

	DECLARE @NEW_CUSTOMERNAME AS VARCHAR(100)
	DECLARE @NEW_BIRTHDATE AS DATE
	DECLARE @NEW_TELNR AS VARCHAR(20)

	SELECT @ID=ID,@OLD_CUSTOMERNAME=CUSTOMERNAME,@OLD_BIRTHDATE=BIRTHDATE,@OLD_TELNR=TELNR 
	FROM deleted

	SELECT @ID=ID,@NEW_CUSTOMERNAME=CUSTOMERNAME,@NEW_BIRTHDATE=BIRTHDATE,@NEW_TELNR=TELNR 
	FROM inserted

	SELECT @ID ID, @OLD_CUSTOMERNAME OLD_CUSTOMERNAME,@OLD_BIRTHDATE OLD_BIRTHDATE,@OLD_TELNR OLD_TELNR
	SELECT @ID ID, @NEW_CUSTOMERNAME NEW_CUSTOMERNAME,@NEW_BIRTHDATE NEW_BIRTHDATE,@NEW_TELNR NEW_TELNR
	PRINT 'SÝLME ÝÞLEMÝ BAÞARI ÝLE GERÇEKLEÞTÝ'
END

INSERT INTO CUSTOMERS(CUSTOMERNAME,BIRTHDATE,TELNR)
VALUES('MUSA UYUMAZ','19990101','05457894561')

UPDATE CUSTOMERS SET CUSTOMERNAME = 'SERHAT UYUMAZ', BIRTHDATE='20040101', TELNR='05234698745' WHERE ID=3