-- 5-Log Trigger-2
CREATE TRIGGER TRG_UPDATEITEMS
ON ITEMS
AFTER UPDATE
AS 
BEGIN
	DECLARE @LOG_ACTIONTYPE VARCHAR(10)='UPDATE'
	DECLARE @LOG_DATE DATETIME
	DECLARE @LOG_HOSTNAME VARCHAR(100)
	DECLARE @LOG_PROGRAMNAME VARCHAR(100)
	DECLARE @LOG_USERNAME VARCHAR(100)

	SET @LOG_DATE = GETDATE()
	SET @LOG_HOSTNAME = HOST_NAME()
	SET @LOG_PROGRAMNAME=PROGRAM_NAME()
	SET @LOG_USERNAME = SUSER_SNAME()

	INSERT INTO LOGDB.DBO.ITEMS(ID, ITEMCODE, ITEMNAME, UNITPRICE, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, BRAND, LOG_ACTIONTYPE, LOG_DATE, LOG_HOSTNAME, LOG_PROGRAMNAME, LOG_USERNAME)
	SELECT ID, ITEMCODE, ITEMNAME, UNITPRICE, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, BRAND, @LOG_ACTIONTYPE, @LOG_DATE, @LOG_HOSTNAME, @LOG_PROGRAMNAME, @LOG_USERNAME FROM deleted
END

SELECT * FROM ITEMS WHERE ID=1
UPDATE ITEMS SET UNITPRICE = 25, ITEMNAME='KODAK PIL XTRA 9V' WHERE ID=1

SELECT * FROM LOGDB.DBO.ITEMS