-- 7-Log Trigger-4
CREATE TRIGGER TRG_UPDATE_DELETE_ITEMS
ON ITEMS
AFTER DELETE,UPDATE
AS 
BEGIN
	DECLARE @LOG_ACTIONTYPE VARCHAR(10)
	DECLARE @INSERTEDCOUNT AS INT
	DECLARE @DELETEDCOUNT AS INT

	SELECT @DELETEDCOUNT=COUNT(*) FROM deleted
	SELECT @INSERTEDCOUNT=COUNT(*) FROM inserted

	IF @DELETEDCOUNT=0 AND @INSERTEDCOUNT>0
		SET @LOG_ACTIONTYPE = 'INSERT'
	ELSE IF @DELETEDCOUNT>0 AND @INSERTEDCOUNT=0
		SET @LOG_ACTIONTYPE = 'DELETE'
	ELSE IF @DELETEDCOUNT>0 AND @INSERTEDCOUNT>0
		SET @LOG_ACTIONTYPE = 'UPDATE'

	DECLARE @LOG_DATE DATETIME
	DECLARE @LOG_HOSTNAME VARCHAR(100)
	DECLARE @LOG_PROGRAMNAME VARCHAR(100)
	DECLARE @LOG_USERNAME VARCHAR(100)

	SET @LOG_DATE = GETDATE()
	SET @LOG_HOSTNAME = HOST_NAME()
	SET @LOG_PROGRAMNAME=PROGRAM_NAME()
	SET @LOG_USERNAME = SUSER_SNAME()

	INSERT INTO LOGDB.DBO.ITEMS(ID, ITEMCODE, ITEMNAME, UNITPRICE, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, BRAND, LOG_ACTIONTYPE, LOG_DATE, LOG_HOSTNAME, LOG_PROGRAMNAME, LOG_USERNAME)
	SELECT ID, ITEMCODE, ITEMNAME, UNITPRICE, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, BRAND, @LOG_ACTIONTYPE, @LOG_DATE, @LOG_HOSTNAME, @LOG_PROGRAMNAME, @LOG_USERNAME FROM deleted
END

SELECT * FROM ITEMS WHERE ID=6

UPDATE ITEMS SET UNITPRICE = 60 WHERE ID=6
DELETE FROM ITEMS  WHERE ID=6

SELECT * FROM LOGDB.DBO.ITEMS

TRUNCATE TABLE LOGDB.DBO.ITEMS