-- 5-View Oluþturma
CREATE VIEW VWORDERS1
AS
SELECT 
O.ID,O.DATE_,
DATENAME(MONTH,O.DATE_) MONTH_,
U.ID USERID, U.USERNAME_, U.NAMESURNAME,U.GENDER,U.EMAIL,U.TELNR1,
A.ADDRESSTEXT,A.POSTALCODE,
C.CITY, T.TOWN,
I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,
OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL,OD.ITEMID
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID

SELECT TOWN,SUM(LINETOTAL) FROM VWORDERS1 WHERE CITY = 'ANKARA'
AND DATE_ BETWEEN '20190501' AND '20190601'
GROUP BY TOWN

ALTER VIEW VWORDERS1
AS
SELECT 
O.ID SIPARISNO,O.DATE_ SIPARISTARIHI,
YEAR(O.DATE_) YIL,
DATENAME(DW,O.DATE_) GUN,
DATENAME(MONTH,O.DATE_) AY,
U.ID KULLANICIID, U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD,U.GENDER CÝNSÝYET,U.EMAIL,U.TELNR1 TELEFON1,
A.ADDRESSTEXT AÇIKADRES,A.POSTALCODE POSTAKODU,
C.CITY ÞEHÝR, T.TOWN ÝLÇE,
I.ITEMCODE ÜRÜNKODU,I.ITEMNAME ÜRÜNADI,I.CATEGORY1 KATEGORÝ1,
OD.AMOUNT MÝKTAR,OD.UNITPRICE BÝRÝMFÝYAT,OD.LINETOTAL SATIRTOPLAMI,OD.ITEMID URUNID
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID

SELECT * FROM VWORDERS1 
WHERE ÞEHÝR='ANKARA'
AND SIPARISTARIHI BETWEEN '20190501' AND '20190601'