-- 6-Dinamik View
-- Bir SQL sorgusunun bir VIEW gibi kullanýldýðý ancak gerçek bir view'ýn oluþturulmadýðý yapýlardýr.
SELECT 
O.ID SIPARISNO,O.DATE_ SIPARISTARIHI,
YEAR(O.DATE_) YIL,
DATENAME(DW,O.DATE_) GUN,
DATENAME(MONTH,O.DATE_) AY,
U.ID KULLANICIID, U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD,U.GENDER CINSIYET,U.EMAIL,U.TELNR1 TELEFON1,
A.ADDRESSTEXT ACIKADRES,A.POSTALCODE POSTAKODU,
C.CITY SEHIR, T.TOWN ILCE,
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.CATEGORY1 KATEGORI1,
OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI,OD.ITEMID URUNID
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID

SELECT AY,SUM(SATIRTOPLAMI) FROM VWORDERS1
GROUP BY AY


SELECT DV.AY,SUM(DV.SATIRTOPLAMI) FROM (
	SELECT 
	O.ID SIPARISNO,O.DATE_ SIPARISTARIHI,
	YEAR(O.DATE_) YIL,
	DATENAME(DW,O.DATE_) GUN,
	DATENAME(MONTH,O.DATE_) AY,
	U.ID KULLANICIID, U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD,U.GENDER CINSIYET,U.EMAIL,U.TELNR1 TELEFON1,
	A.ADDRESSTEXT ACIKADRES,A.POSTALCODE POSTAKODU,
	C.CITY SEHIR, T.TOWN ILCE,
	I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.CATEGORY1 KATEGORI1,
	OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI,OD.ITEMID URUNID
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN USERS U ON U.ID = O.USERID
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	JOIN TOWNS T ON T.ID = A.TOWNID
) DV
GROUP BY DV.AY