-- 7-View Alýþtýrma-1
-- Elimizde bir E-Ticaret sistemini dataseti var. Bu dataset üzerinde aylara göre satýþý getirecek VWMONTHLYSALES isimli bir view oluþturunuz.
-- Kaynak DB: ETRADE-RDMS

CREATE VIEW VWMONTHLYSALES
AS
SELECT DATEPART(MONTH,DATE_) MONTHNR,DATENAME(MONTH,DATE_) MONTHNAME_,SUM(TOTALPRICE) TOTALSALE FROM ORDERS
GROUP BY DATEPART(MONTH,DATE_),DATENAME(MONTH,DATE_)

SELECT MONTHNAME_,TOTALSALE FROM VWMONTHLYSALES
ORDER BY MONTHNR

ALTER VIEW VWMONTHLYSALES
AS
SELECT 
CASE 
	WHEN MONTH(DATE_)=1 THEN '01.OCAK'
	WHEN MONTH(DATE_)=2 THEN '02.SUBAT'
	WHEN MONTH(DATE_)=3 THEN '03.MART'
	WHEN MONTH(DATE_)=4 THEN '04.NISAN'
	WHEN MONTH(DATE_)=5 THEN '05.MAYIS'
	WHEN MONTH(DATE_)=6 THEN '06.HAZIRAN'
	WHEN MONTH(DATE_)=7 THEN '07.TEMMUZ'
	WHEN MONTH(DATE_)=8 THEN '08.AGUSTOS'
	WHEN MONTH(DATE_)=9 THEN '09.EYLUL'
	WHEN MONTH(DATE_)=10 THEN '10.EKIM'
	WHEN MONTH(DATE_)=11 THEN '11.KASIM'
	WHEN MONTH(DATE_)=12 THEN '12.ARALIK'
END AS MONTHNAME_,SUM(TOTALPRICE) TOTALSALE FROM ORDERS
GROUP BY MONTH(DATE_)

SELECT * FROM VWMONTHLYSALES 
ORDER BY 1