-- 8-View Alýþtýrma-2
-- Elimizde bir E-Ticaret sisteminin dataseti var. Bu dataset içinde sipariþlerin ortalama hazýrlýk sürelerini hesaplayan VWINVOICEDURATION isimli bir view oluþturunuz.
-- Kaynak Tablo: ETRADE-RDMS
SELECT * FROM ORDERS
SELECT * FROM INVOICES
SELECT * FROM INVOICEDETAILS
SELECT * FROM ADDRESS
SELECT * FROM CITIES

CREATE VIEW VWINVOICEDURATION
AS
SELECT C.CITY SEHIR,AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) ORT_HAZIRLIK_SURESI FROM INVOICES I 
JOIN ORDERS O ON O.ID = I.ORDERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
GROUP BY C.CITY

SELECT * FROM VWINVOICEDURATION