CREATE FUNCTION DBO.MONTHNAME_(@DATE AS DATETIME)
RETURNS VARCHAR(10)
AS 
BEGIN DECLARE @RESULT AS VARCHAR(10)

IF DATEPART(MONTH,@DATE)=1 SET @RESULT='01.OCK'
IF DATEPART(MONTH,@DATE)=2 SET @RESULT='02.ÞUB'
IF DATEPART(MONTH,@DATE)=3 SET @RESULT='03.MAR'
IF DATEPART(MONTH,@DATE)=4 SET @RESULT='04.NIS'
IF DATEPART(MONTH,@DATE)=5 SET @RESULT='05.MAY'
IF DATEPART(MONTH,@DATE)=6 SET @RESULT='06.HAZ'
IF DATEPART(MONTH,@DATE)=7 SET @RESULT='07.TEM'
IF DATEPART(MONTH,@DATE)=8 SET @RESULT='08.AÐU'
IF DATEPART(MONTH,@DATE)=9 SET @RESULT='09.EYL'
IF DATEPART(MONTH,@DATE)=10 SET @RESULT='10.EKM'
IF DATEPART(MONTH,@DATE)=11 SET @RESULT='11.KAS'
IF DATEPART(MONTH,@DATE)=12 SET @RESULT='12.ARA'
RETURN @RESULT
END

CREATE FUNCTION DBO.DAYOFWEEK_(@DATE AS DATETIME)
RETURNS VARCHAR(10)
AS 
BEGIN DECLARE @RESULT AS VARCHAR(10)

IF DATEPART(DW,@DATE)=2 SET @RESULT='01.PZT'
IF DATEPART(DW,@DATE)=3 SET @RESULT='02.SAL'
IF DATEPART(DW,@DATE)=4 SET @RESULT='03.ÇAR'
IF DATEPART(DW,@DATE)=5 SET @RESULT='04.PER'
IF DATEPART(DW,@DATE)=6 SET @RESULT='05.CUM'
IF DATEPART(DW,@DATE)=7 SET @RESULT='06.CMT'
IF DATEPART(DW,@DATE)=1 SET @RESULT='07.PZR'
RETURN @RESULT
END



