SELECT ITM.ID,ITM.ITEMCODE MALZEMEKODU,ITM.ITEMNAME MALZEMEADI,
DBO.GET_ITEM_PRICE(ITM.ID,'MIN') AS ENDUSUKFIYAT,
DBO.GET_ITEM_PRICE(ITM.ID,'MAX') AS ENYUKSEKFIYAT,
DBO.GET_ITEM_PRICE(ITM.ID,'AVG') AS ORTALAMAFIYAT,
DBO.GET_ITEM_TOTALSALE(ITM.ID) AS TOPLAMSATIS
FROM ITEMS ITM