--ÜRÜN ANALÝZÝ
SET STATISTICS TIME ON
SELECT ITM.ID,ITM.ITEMCODE MALZEMEKODU,ITM.ITEMNAME MALZEMEADI,
ITEMINFO.MINPRICE AS ENDUSUKFIYAT,
ITEMINFO.MAXPRICE AS ENYUKSEKFIYAT,
ITEMINFO.AVGPRICE AS ORTALAMAFIYAT,
ITEMINFO.TOTALSALE AS TOPLAMSATISTUTAR,
ITEMINFO.TOTALAMOUNT AS TOPLAMSATISMIKTAR
FROM ITEMS ITM
CROSS APPLY DBO.GET_ITEM_INFO(ITM.ID) AS ITEMINFO