CREATE FUNCTION DBO.CALCULATE_AGE(@BIRTHDATE AS DATE)
RETURNS INT
AS 
BEGIN 
DECLARE @RESULT AS INT 
SET @RESULT=DATEDIFF(YEAR,@BIRTHDATE,GETDATE())

RETURN @RESULT
END

SELECT DBO.CALCULATE_AGE('19900101')

SELECT DATEDIFF(YEAR,'19900101',GETDATE())

SELECT TOP 1000 *, DBO.CALCULATE_AGE(BIRTHDATE) AS AGE FROM CUSTOMERS