--ÜRÜN ANALÝZÝ
SELECT 
ITM.ITEMCODE MALZEMEKODU,ITM.ITEMNAME MALZEMEADI,MIN(OD.UNITPRICE) AS ENDUSUKFIYAT,
MAX(OD.UNITPRICE) AS ENYUKSEKFIYAT,AVG(OD.UNITPRICE) AS ORTALAMAFIYAT,
SUM(OD.LINETOTAL) AS TOPLAMSATISTUTAR, SUM(OD.AMOUNT) AS TOPLAMSATISMIKTAR
FROM ORDERDETAILS AS OD 
INNER JOIN ORDERS AS O ON O.ID = OD.ORDERID
INNER JOIN ITEMS AS ITM ON ITM.ID = OD.ITEMID 
GROUP BY ITM.ITEMCODE,ITM.ITEMNAME