CREATE FUNCTION DBO.GET_ITEM_MINPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS 
BEGIN
DECLARE @RESULT AS FLOAT
	SELECT @RESULT=MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID
	RETURN @RESULT
END
CREATE FUNCTION DBO.GET_ITEM_MAXPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS 
BEGIN
DECLARE @RESULT AS FLOAT
	SELECT @RESULT=MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID
	RETURN @RESULT
END
CREATE FUNCTION DBO.GET_ITEM_AVGPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS 
BEGIN
DECLARE @RESULT AS FLOAT
	SELECT @RESULT=AVG(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID
	RETURN @RESULT
END
CREATE FUNCTION DBO.GET_ITEM_TOTALSALE(@ITEMID AS INT)
RETURNS FLOAT
AS 
BEGIN
DECLARE @RESULT AS FLOAT
	SELECT @RESULT=SUM(LINETOTAL) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID
	RETURN @RESULT
END


SELECT DBO.GET_ITEM_MINPRICE(84)