--ÜRÜN ANALÝZÝ
SELECT ITM.ID,ITM.ITEMCODE MALZEMEKODU,ITM.ITEMNAME MALZEMEADI,
--(SELECT MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = ITM.ID) AS ENDUSUKFIYAT,
--(SELECT MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = ITM.ID) AS ENYUKSEKFIYAT
DBO.GET_ITEM_MINPRICE(ITM.ID) AS ENDUSUKFIYAT,
DBO.GET_ITEM_MAXPRICE(ITM.ID) AS ENYUKSEKFIYAT,
DBO.GET_ITEM_AVGPRICE(ITM.ID) AS ORTALAMAFIYAT,
DBO.GET_ITEM_TOTALSALE(ITM.ID) AS TOPLAMSATIS
FROM ITEMS ITM

--UPDATE STATISTICS ORDERDETAILS