-- 4-Döngüler Alýþtýrma-2
-- Bir önceki alýþtýrmada yaptýðýmýz termometre örneði üzerinden gün içerisinde 30 saniyede bir ölçüm yapan bir sistem oluþturunuz ve 30 saniyede bir termometrelerden rastgele deðer okuyup bu deðerleri loglayacak bir mekanizma kuracak þekilde TSQL kodunu yazýnýz.
-- Kaynak DB: LAB_LOOPS
-- Kaynak Tablo: LAB02

SELECT * FROM LAB02_DEVICES
SELECT * FROM LAB02_LOG

TRUNCATE TABLE LAB02_LOG
UPDATE LAB02_DEVICES SET CURRENTVALUE = 0


DECLARE @I INT = 1
WHILE 1=1
BEGIN
	WHILE  @I <= 100
	BEGIN 
		UPDATE LAB02_DEVICES SET CURRENTVALUE= 18 + ROUND(RAND() * 5,2) WHERE ID=@I
		SET @I=@I + 1
	END
	INSERT INTO LAB02_LOG([DEVICEID], [DATE_], [VALUE_])
	SELECT ID,GETDATE(),CURRENTVALUE FROM LAB02_DEVICES
	SELECT * FROM LAB02_LOG
	WAITFOR DELAY '00:00:30'
END



DECLARE @DEVICEID AS INT = 1
DECLARE @DATE AS DATETIME ='2022-02-27 07:30:00'
DECLARE @CURRENTVALUE AS FLOAT
DECLARE @NEWVALUE AS FLOAT
DECLARE @I2 AS INT=1

WHILE @I2<=100
BEGIN 
	@DEVICEID = @I2
	@DATE = '2022-02-27 07:30:00'
	WHILE @DATE <= '2022-08-27 07:32:00'
	BEGIN 
		SELECT @CURRENTVALUE=CURRENTVALUE FROM LAB02_DEVICES WHERE ID=@DEVICEID
		IF @CURRENTVALUE=0
		BEGIN
			SET @CURRENTVALUE = 18
		END
		SET @NEWVALUE = ROUND(@CURRENTVALUE-0.5+RAND(),2)
		UPDATE LAB02_DEVICES SET CURRENTVALUE = @NEWVALUE WHERE ID=@DEVICEID
		INSERT INTO LAB02_LOG(DEVICEID,DATE_,VALUE_) VALUES(@DEVICEID,@DATE,@NEWVALUE)
		SET @DATE = DATEADD(SECOND,30,@DATE)
	END
	SET @I2=@I2+1
END

