SELECT * FROM MONEYTRANSACTIONS
SELECT C.CUSTOMERNAME,A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM ACCOUNTBALANCE B
INNER JOIN ACCOUNTS A ON A.ID=B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID=A.CUSTOMERID


BEGIN TRAN
INSERT INTO MONEYTRANSACTIONS([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [EFTCODE1], [EFTCODE2])
VALUES(1,2,1000,'2020-04-14 14:21:36','1234567','')
IF @@ERROR > 0
BEGIN 
	ROLLBACK TRAN
	RETURN
END
	
UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE-1000 WHERE ACCOUNTID=1
IF @@ERROR > 0
BEGIN 
	ROLLBACK TRAN
	RETURN
END

INSERT INTO MONEYTRANSACTIONS([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [EFTCODE1], [EFTCODE2])
VALUES(2,1,1000,'2020-04-14 15:21:36','1234567','ABCDEF0987654321')
IF @@ERROR > 0
BEGIN 
	ROLLBACK TRAN
	RETURN
END


UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE+1000 WHERE ACCOUNTID=2
IF @@ERROR > 0
BEGIN 
	ROLLBACK TRAN
	RETURN
END

COMMIT TRAN