--AHMET ÖMER'E 1.000 TL PARA GÖNDERÝYOR

SELECT * FROM CUSTOMERS

SELECT * FROM ACCOUNTS 

SELECT C.CUSTOMERNAME,A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM ACCOUNTBALANCE B 
INNER JOIN ACCOUNTS A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID=A.CUSTOMERID