SELECT * FROM CUSTOMERS WHERE NAMESURNAME = 'ÖMER ÇOLAKOÐLU'

SELECT * FROM CUSTOMERS WHERE ID= 168483

SET STATISTICS IO ON
SELECT * FROM CUSTOMERS WHERE TELNR='03423344747'

SET STATISTICS IO ON
SELECT * FROM CUSTOMERS WHERE NAMESURNAME = 'ÖMER ÇOLAKOÐLU' OR TELNR='03423344747'

SET STATISTICS IO ON
SELECT * FROM CUSTOMERS WHERE BIRTHDATE='1964-03-30' AND NAMESURNAME = 'ÖMER ÇOLAKOÐLU'