-- 10 -Stored Procedure Alýþtýrma-3
-- Elimizde kullanýcýlarýn tutulduðu bir tablo var. Bu tabloda login iþlemini gerçekleþtirecek, içine kullanýcý adý, mail adresi, þifre ve ip bilgisini alacak bir stored procedure'ü yazýnýz. Procedure ayný zamanda login olma iþlemini otomatik olarak kayýt altýna alacaktýr.
-- Kaynak DB: LAB_SP
-- Kaynak Tablo: LAB_USER, LAB_USERLOGIN_LOG

ALTER PROC SP_LOGIN
@USERNAMEOREMAIL AS VARCHAR(100) = NULL,
@PASSWORD AS VARCHAR(50),
@IPADDRESS AS VARCHAR(50)
AS
DECLARE @USERID AS INT
DECLARE @LOGINTYPE AS VARCHAR(100)

SELECT @USERID=ID FROM LAB_USER 
WHERE (USERNAME_ = @USERNAMEOREMAIL OR EMAIL = @USERNAMEOREMAIL) 
AND PASSWORD_ = @PASSWORD

IF @USERID > 0
BEGIN
	SET @LOGINTYPE = 'GÝRÝÞ BAÞARILI'
	INSERT LAB_USERLOGIN_LOG(USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_) VALUES(@USERID,@USERNAMEOREMAIL,@LOGINTYPE,@IPADDRESS,GETDATE())
END
ELSE 
BEGIN
	SET @LOGINTYPE = 'GÝRÝÞ BAÞARISIZ'
	INSERT LAB_USERLOGIN_LOG(USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_) VALUES(@USERID,@USERNAMEOREMAIL,@LOGINTYPE,@IPADDRESS,GETDATE())
END
SELECT * FROM LAB_USERLOGIN_LOG WHERE @USERID = @USERID


--INSERT LAB_USERLOGIN_LOG VALUES()
--SELECT * FROM LAB_USERLOGIN_LOG

EXEC SP_LOGIN 
'N_OZSIMITCI',
@PASSWORD = '4598751',
@IPADDRESS='136.58.96.214'