-- 12 -Stored Procedure Alýþtýrma-5
-- Elimizde StackOverFlow'un yorumlarýnýn olduðu dataset var. Bu dataset içinde belli bir kelimenin geçtiði yorumlarý bulan ve içine aranacak kelime, baþlangýç ve bitiþ tarihlerini alan bir stored procedure yazýnýz. Bu procedure'ün içine gönderdiðimiz parametreler ile ne zaman kim tarafýndan hangi parametreler ile çalýþtýrýþdýðýný ne kadar sürdüðünü ve kayýt sayýsýný loglayan procedure'ü yazýnýz
-- Kaynak DB: LAB_SP
-- Kaynak Tablo: LAB_STACKOVERFLOW

ALTER PROC SP_SEARCH
@BEGDATE AS DATETIME,
@ENDDATE AS DATETIME,
@STRTOSEARCH AS VARCHAR(200)
AS
DECLARE @USERNAME AS VARCHAR(50)
DECLARE @PROCNAME AS VARCHAR(100)='SP_SEARCH'
DECLARE @PARAMETERS AS VARCHAR(250)
DECLARE @PBEGDATE AS DATETIME
DECLARE @PENDDATE AS DATETIME
DECLARE @DURATION AS INT

SET @USERNAME=SUSER_NAME()
SET @PARAMETERS='@BEGDATE:'+CONVERT(VARCHAR,@BEGDATE,104)+CHAR(13)+'@ENDDATE:'+CONVERT(VARCHAR,@ENDDATE,104)+CHAR(13)+'@STRTOSEARCH:'+@STRTOSEARCH
SET @PBEGDATE = GETDATE()

SELECT  * FROM LAB_STACKOVERFLOW
WHERE CreationDate BETWEEN @BEGDATE AND @ENDDATE
AND TEXT LIKE '%'+@STRTOSEARCH+'%'

SET @PENDDATE = GETDATE()
SET @DURATION = DATEDIFF(SECOND,@PBEGDATE,@PENDDATE)

INSERT INTO PROCEDURE_EXECUTION_LOG(USERNAME_,PROCNAME,PARAMETERS,BEGDATE,ENDDATE,DURATION)
VALUES(@USERNAME,@PROCNAME,@PARAMETERS,@PBEGDATE,@PENDDATE,@DURATION)

PRINT @PARAMETERS

-- PROCEDURE USING
SP_SPACEUSED LAB_STACKOVERFLOW

EXEC SP_SEARCH @BEGDATE='20100101',@ENDDATE='20101231',@STRTOSEARCH='Microsoft SQL Server'
--SELECT * FROM PROCEDURE_EXECUTION_LOG