-- 5-Stored Procedure'de Default Deðer Tanýmlama

ALTER PROCEDURE SP_GETSALES 
@CITY AS VARCHAR(50)='%',
@BEGDATE DATE = NULL,
@ENDDATE DATE = NULL
AS
SET @BEGDATE = ISNULL(@BEGDATE,'20190101')
SET @ENDDATE = ISNULL(@ENDDATE,'20190401')
SELECT * FROM SALES WHERE CITY LIKE @CITY AND DATE_ BETWEEN @BEGDATE AND @ENDDATE
ORDER BY DATE_


EXEC SP_GETSALES @CITY='ADANA', @BEGDATE='20190201', @ENDDATE='20190301'