-- 6-Raiseerror Ýle Hata Bastýrma

ALTER PROC SP_GETORDERS
@USERNAME AS VARCHAR(100),
@BEGDATE AS DATETIME,
@ENDDATE AS DATETIME,
@CITY AS VARCHAR(100)
AS

IF DATEDIFF(MONTH,@BEGDATE,@ENDDATE) > 3
BEGIN 
	RAISERROR('Lütfen 3 aydan daha kýsa bir aralýk giriniz!',16,1)
	RETURN
END

SELECT 
O.ID,O.DATE_,
U.USERNAME_,U.NAMESURNAME,
C.CITY,
T.TOWN,
D.DISTRICT,
A.POSTALCODE,A.ADDRESSTEXT,
I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.CATEGORY4,I.UNITPRICE ITEMPRICE, 
OD.UNITPRICE,OD.AMOUNT,OD.LINETOTAL
FROM ORDERS O 
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID =A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE U.USERNAME_ LIKE @USERNAME 
AND O.DATE_ BETWEEN @BEGDATE AND @ENDDATE
AND C.CITY LIKE @CITY

EXEC SP_GETORDERS 
@USERNAME='E_BEKTAS',
@BEGDATE='20190501',
@ENDDATE='20190930',
@CITY='%'