-- 9-Stored Procedure Alýþtýrma-2
-- Elimizde rastgele oluþturulan plakalardan oluþan bir araç veritabaný var. Bu araç veritabanýný kullanarak içine araç markasý ve trafiðe çýkýþ tarihi baþlangýç-bitiþ parametreleri ile bölgeleri liste olarak göndereceðimiz ve her bir þehirde kiþi baþýna düþen araç sayýsýný hem toplam araç bazýnda hem de marka bazýnda getirecek Stored Procedure'ü yazýnýz.
-- Kaynak DB: LAB_SP
-- Kaynak Tablo: LAB_PLATES,LAB_CITIES

ALTER PROC SP_GETVEHICLES
@BRAND AS VARCHAR(100) = '%',
@BEGDATE AS DATE,
@ENDDATE AS DATE,
@REGION AS VARCHAR(200)
AS
SELECT C.CITYNAME SEHIR,
C.POPULATION NUFUS,
C.REGION BOLGE,
COUNT(P.PLATE) ARACSAYISI,
ROUND((COUNT(P.PLATE) / CONVERT(float,C.POPULATION)),3) KISIBASI_ARACSAYISI 
FROM LAB_PLATES P
INNER JOIN LAB_CITIES C ON C.ID = P.CITYNR
WHERE REGION IN (SELECT VALUE FROM string_split(@REGION,',')) 
AND BRAND LIKE @BRAND 
AND LICENCEDATE BETWEEN @BEGDATE AND @ENDDATE
GROUP BY C.CITYNAME,C.POPULATION,C.REGION
ORDER BY 1

SELECT C.CITYNAME SEHIR,
C.POPULATION NUFUS,
C.REGION BOLGE,
P.BRAND MARKA ,
COUNT(P.PLATE) ARACSAYISI,
ROUND((COUNT(P.PLATE) / CONVERT(float,C.POPULATION)),3) KISIBASI_ARACSAYISI 
FROM LAB_PLATES P
INNER JOIN LAB_CITIES C ON C.ID = P.CITYNR
WHERE REGION IN (SELECT VALUE FROM string_split(@REGION,',')) 
AND BRAND LIKE @BRAND 
AND LICENCEDATE BETWEEN @BEGDATE AND @ENDDATE
GROUP BY C.CITYNAME,C.POPULATION,P.BRAND,C.REGION
ORDER BY 1

EXEC SP_GETVEHICLES
@BRAND = '%',
@BEGDATE = '20000101',
@ENDDATE = '20221231',
@REGION = 'ÝÇ ANADOLU'