-------------------------------------DATETIME FONKSÝYONLARI------------------------------------
--DATEADD --> Bir tarihe belli deðeri ekleme fonksiyonu
DECLARE @TARIH AS DATETIME
SET @TARIH = '2019-01-01 16:21:37'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2=DATEADD(MONTH,6,@TARIH)
SET @TARIH2=DATEADD(DAY,6,@TARIH)
SET @TARIH2=DATEADD(HOUR,6,@TARIH)
SET @TARIH2=DATEADD(HOUR,16,@TARIH)
SELECT @TARIH,@TARIH2

--DATEDIFF --> Iki tarih arasýnda fark alan fonksiyon
DECLARE @TARIH AS DATETIME
SET @TARIH = '2019-01-01 16:21:37'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2 = '2020-01-07 16:21:37'

SELECT DATEDIFF(WEEK,@TARIH,@TARIH2)

--DATEFROMPARTS --> Bizim elimizde yýl ay gün parametreleri olabilir ve biz bu deðerlerden bir datetime deðiþken elde etmek isteyebiliriz bunun için bu fonksiyonu kullanýrýz.
DECLARE @TARIH AS DATETIME
SET @TARIH = DATEFROMPARTS(2020,8,21)
SELECT @TARIH

--DATEPART --> Bir tarihin istediðin kýsmýný sana getirir
DECLARE @TARIH AS DATETIME
SET @TARIH = DATEFROMPARTS(2020,8,21)
SELECT DATEPART(MONTH,@TARIH)

SELECT YEAR(@TARIH)

--GETDATE --> Þimdiki zamani getirir.
SELECT GETDATE()

DECLARE @TARIH AS DATE
	SET @TARIH= '1999-02-14'
	SELECT DATEDIFF(HOUR,@TARIH,GETDATE())