-- SQL'de deðiþken tanýmlarken kullandýðýmýz komut DECLARE'dir
-- Sonrasýnda deðiþkenin ismini yazarýz. Ama deðiþkenin adýný yazarken baþýna @ iþareti koyarýz.
-- Sonrasýnda bunun tipini yazarýz.
-- SELECT komutu deðer çekmek için de kullanýlýr.

--DECLARE @ISIM AS VARCHAR(100) = 'MUSA'
--DECLARE @ISIM AS VARCHAR(100)
--SET @ISIM = 'MUSA'
--SELECT @ISIM


--DECLARE @SAYI AS INTEGER
--SET @SAYI=15
--DECLARE @SAYI2 AS INTEGER
--SET @SAYI2 = 20
--DECLARE @TOPLAM AS INTEGER
--SET @TOPLAM = @SAYI + @SAYI2

--SELECT @SAYI AS SAYI1, @SAYI2 AS SAYI2, @TOPLAM AS TOPLAM


--DECLARE @SAYI AS INTEGER,
--@SAYI2 AS INTEGER,
--@TOPLAM AS INTEGER

--SET @SAYI=15
--SET @SAYI2 = 20
--SET @TOPLAM = @SAYI + @SAYI2

--SELECT @SAYI AS SAYI1, @SAYI2 AS SAYI2, @TOPLAM AS TOPLAM

SELECT * FROM ISIMLER

DECLARE @ISIM AS VARCHAR(100)
DECLARE @TELEFON AS VARCHAR(100)

SELECT @ISIM = ISIM, @TELEFON=TELEFON  FROM ISIMLER WHERE ID=1

SELECT @ISIM, @TELEFON

DECLARE @TARIH AS DATETIME
SET @TARIH = GETDATE()

SELECT @TARIH