--TSQL'de for döngüsü yoktur while döngüsü vardýr.

--DECLARE  @I AS INT= 0
--WHILE @I < 10
--BEGIN
--PRINT @I
--SET @I=@I+1
--END

DECLARE  @I AS INT= 0
WHILE @I < 10
BEGIN
	INSERT INTO TARIHLER (TARIH) VALUES (GETDATE())
	WAITFOR DELAY '00:00:01'
	SET @I=@I+1
END

TRUNCATE TABLE TARIHLER
SELECT * FROM TARIHLER